name: az400-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main # Runs pipeline when code is commited to main branch
  paths:
    include:
      - lab/**

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo "Hello world, Azure DevOps Pipeline is running!"
    displayName: "Run a simple script"
